name: iOS CI

on:
  push:
    branches:
      - main
      - feature/rest-countries-implementation

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build App
        run: |
          xcodebuild -scheme RestCountries -sdk iphonesimulator build

      - name: Run Tests
        run: |
          xcodebuild test \
          -scheme RestCountries \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=Any iOS Simulator Device'
